[Icon Theme]
Name=NineIcons48x
Comment=Nine Icons with custom 48px icons
Inherits=mate,Adwaita,hicolor
Example=folder
Directories=actions/22,apps/16,apps/32,categories/16,categories/32,devices/16,devices/32,mimes/16,mimes/32,mimes/48,places/16,places/22,places/24,places/32,places/48,status/16

[actions/22]
Size=22
Context=Actions
Type=Fixed

[apps/16]
Size=16
Context=Applications
Type=Fixed

[apps/32]
Size=32
Context=Applications
Type=Fixed

[categories/16]
Size=16
Context=Categories
Type=Fixed

[categories/32]
Size=32
Context=Categories
Type=Fixed

[devices/16]
Size=16
Context=Devices
Type=Fixed

[devices/32]
Size=32
Context=Devices
Type=Fixed

[mimes/16]
Size=16
Context=MimeTypes
Type=Fixed

[mimes/32]
Size=32
Context=MimeTypes
Type=Fixed

[mimes/48]
Size=48
Context=MimeTypes
Type=Fixed

[places/16]
Size=16
Context=Places
Type=Fixed

[places/32]
Size=32
Context=Places
Type=Fixed

[places/48]
Size=48
Context=Places
Type=Fixed

[status/16]
Size=16
Context=Status
Type=Fixed

[places/22]
Size=22
Context=Places
Type=Fixed

[places/24]
Size=24
Context=Places
Type=Fixed
