#!/usr/bin/env bash

set -eu

state="${QUARTZ_FAKE_GSETTINGS_STATE:?}"
command_name="$1"
shift

case "$command_name" in
  list-schemas)
    printf '%s\n' org.mate.interface org.mate.panel
    ;;
  writable)
    printf 'true\n'
    ;;
  get)
    schema="$1"
    key="$2"
    case "$schema:$key" in
      org.mate.interface:gtk-theme)
        cat "$state/theme"
        ;;
      org.mate.panel:toplevel-id-list)
        printf "['top', 'bottom', 'left']\n"
        ;;
      *toplevels/*)
        case "$schema" in
          *toplevels/top/*) panel_id=top ;;
          *toplevels/bottom/*) panel_id=bottom ;;
          *toplevels/left/*) panel_id=left ;;
          *) exit 1 ;;
        esac
        cat "$state/$panel_id/$key"
        ;;
      *)
        exit 1
        ;;
    esac
    ;;
  set)
    schema="$1"
    key="$2"
    value="$3"
    case "$schema" in
      *toplevels/top/*) panel_id=top ;;
      *toplevels/bottom/*) panel_id=bottom ;;
      *) exit 1 ;;
    esac
    case "$panel_id" in
      top|bottom)
        if [[ "$key" == "type" || "$key" == "image" || "$key" == "orientation" ]]; then
          printf "'%s'\n" "$value" >"$state/$panel_id/$key"
        else
          printf '%s\n' "$value" >"$state/$panel_id/$key"
        fi
        printf '%s:%s=%s\n' "$panel_id" "$key" "$value" >>"$state/../set.log"
        ;;
      *)
        exit 1
        ;;
    esac
    ;;
  *)
    exit 1
    ;;
esac
